markdown:         rdiscount
rdiscount:
  extensions:     [smart]
highlighter:      pygments

permalink:        pretty

title:            Shelby Switzer
tagline:          'A blog'
description:      'language junkie'
url:              http://switzersc.github.io

author:
  name:           'Shelby Switzer'
  url:            https://twitter.com/switzerly

paginate:         5

google_analytics:
links:
  - name:         About
    url:          /about