markdown:         kramdown
rdiscount:
  extensions:     [smart]
highlighter:      rouge

permalink:        /blog/:year/:month/:day/:title

title:            Shelby Switzer
tagline:          'Homepage of Shelby Switzer'
description:      'Writer and Civic Technologist'
url:              http://switzersc.github.io

author:
  name:           'Shelby Switzer'
  url:            https://twitter.com/switzerly

paginate:         5

google_analytics:
links:

gems:
  - jekyll-redirect-from
  - jekyll-paginate